version: "3.9"
services:
  database-service:
    image: postgres:14
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: yourname
      POSTGRES_PASSWORD: yourpassword
      POSTGRES_DB: mydb
      PGDATA: /data/postgres
    ports:
      - 5432:5432
    env_file: "./.env"

  express-gql-prisma:
    image: express-gql-prisma
    container_name: express-gql-prisma
    restart: always
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    ports:
      - "4000:4000"
    depends_on:
      - database-service
    env_file: "./.env"
